[2024-03-21 02:40:35,073][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x749250245760>: Failed to establish a new connection: [Errno 110] Connection timed out')': /v1/engines/text-davinci-002/completions
